# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1007401224f4ec4fe31ff3f880da2357efaf92a1a5a10f431ca6e1bfd693b6b56cc7de7e4f992c1d3ff585061b9029a04d8fea8a35edc53e18ed0af983f9df57

test:
  secret_key_base: bed3f723bfed017c31d0bb9b2fd98794a9b137d7fdf407c90c6547ddd96e8c463e47c125ffb15977b489a7084fa0af4fcc59aecdfd66214eaffaab4956e1987f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
